const express = require("express");
const authRoutes = require("./routes/authRoutes");
const roleRoutes = require("./routes/roleRoutes");
const planRoutes = require("./routes/planRoutes");
const axeRoutes = require("./routes/axeRoutes");
const priorityRoutes = require("./routes/priorityRoutes");
const projetRoutes = require("./routes/projetRoutes");
const tacheRoutes = require("./routes/tacheRoutes");
const indicateurRoutes = require("./routes/indicateurRoutes");
const evaluationRoutes = require("./routes/evaluationRoutes");
const permissionRoutes = require("./routes/permissionRoutes");
const role_permissionRoutes = require("./routes/role_permissionRoutes");
const groupeRoutes = require("./routes/groupeRoutes");
const ressourceRoutes = require("./routes/ressourceRoutes");
const commentaireRoutes = require("./routes/commentaireRoutes");
const actualiteRoutes = require("./routes/actualiteRoutes");
const suggestionRoutes = require("./routes/suggestionRoutes");
const actualite_imageRoutes = require("./routes/actualite_imagesRoutes");
const newsletterRoutes = require("./routes/newsletterRoutes");
const voteRoutes = require("./routes/voteRoutes");
const documentRoutes = require("./routes/documentRoutes");
const groupeutilisateurRoutes = require("./routes/groupeutilisateurRoutes");
const projet_groupeRoutes = require("./routes/projet_groupesRoutes");
const projet_utilisateurRoutes = require("./routes/projet_utilisateurRoutes");
const tache_groupeRoutes = require("./routes/tache_groupeRoutes");
const tache_utilisateurRoutes = require("./routes/tache_utilisateurRoutes");
const notificationRoutes = require("./routes/notificationRoutes");
const app = express();
app.use(express.json());

app.use("/auth", authRoutes);
app.use("/role", roleRoutes);
app.use("/plan", planRoutes);
app.use("/axe", axeRoutes);
app.use("/priority", priorityRoutes);
app.use("/projet", projetRoutes);
app.use("/tache", tacheRoutes);
app.use("/indicateur", indicateurRoutes);
app.use("/evaluation", evaluationRoutes);
app.use("/permission", permissionRoutes);
app.use("/role_permission", role_permissionRoutes);
app.use("/groupe", groupeRoutes);
app.use("/ressource", ressourceRoutes);
app.use("/commentaire", commentaireRoutes);
app.use("/actualite", actualiteRoutes);
app.use("/suggestion", suggestionRoutes);
app.use("/actualite_image", actualite_imageRoutes);
app.use("/newsletter", newsletterRoutes);
app.use("/vote", voteRoutes);
app.use("/document", documentRoutes);
app.use("/groupeutilisateur", groupeutilisateurRoutes);
app.use("/projet_groupe", projet_groupeRoutes);
app.use("/projet_utilisateur", projet_utilisateurRoutes);
app.use("/tache_groupe", tache_groupeRoutes);
app.use("/tache_utilisateur", tache_utilisateurRoutes);
app.use("/notification", notificationRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Serveur en cours d'exécution sur le port ${PORT}`);
});
